# Generated by Django 4.0.1 on 2022-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=50)),
                ('SUBTITLE', models.CharField(max_length=50, null=True)),
                ('AUTHOR', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('PUBLISHER', models.CharField(max_length=20)),
                ('PRICE', models.CharField(max_length=30)),
                ('PAGE', models.CharField(max_length=20, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('BOOK_INDEX', models.TextField(verbose_name='목차')),
                ('BOOK_INTRODUCTION', models.TextField(verbose_name='소개')),
                ('PUBLISH_DATE', models.DateField(null=True)),
                ('RATING', models.FloatField(default=2.5)),
                ('Allah_BID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('pwToekn', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='북아무개', max_length=10)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('pushNoti', models.BooleanField(default=False)),
                ('pushToken', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
