# Generated by Django 4.0.1 on 2022-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=50)),
                ('VOL', models.CharField(max_length=20, null=True)),
                ('AUTHOR', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('PUBLISHER', models.CharField(max_length=20)),
                ('PRICE', models.IntegerField(null=True)),
                ('PAGE', models.CharField(max_length=20, null=True)),
                ('SUBJECT', models.CharField(max_length=20, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('BOOK_INDEX', models.CharField(max_length=255, null=True)),
                ('BOOK_INTRODUCTION', models.CharField(max_length=255, null=True)),
                ('BOOK_SUMMARY', models.CharField(max_length=255, null=True)),
                ('PUBLISH_DATE', models.DateField()),
                ('UPDATE_DATE', models.DateField(null=True)),
                ('TAG', models.CharField(max_length=100)),
                ('RATING', models.FloatField(default=2.5)),
                ('Allah_BID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pwToekn', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('nickname', models.CharField(default='ABC', max_length=10)),
                ('pushToken', models.CharField(max_length=255)),
            ],
        ),
    ]
