# Generated by Django 4.0.1 on 2022-03-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pwToekn',
            new_name='pwToken',
        ),
    ]
