# Generated by Django 4.0.3 on 2022-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AUTHOR',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='BOOK_INTRODUCTION',
            field=models.TextField(null=True, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='PUBLISHER',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
