# Generated by Django 4.0.3 on 2022-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationCodeStorage',
            fields=[
                ('ATCID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('authCode_token', models.CharField(max_length=255)),
                ('createAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='refreshtokenstorage',
            name='createAt',
            field=models.DateField(auto_now=True),
        ),
    ]
