# Generated by Django 4.0.3 on 2022-03-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0002_authenticationcodestorage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationcodestorage',
            name='ATCID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
