# Generated by Django 4.0.1 on 2022-03-18 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0002_rename_pwtoekn_user_pwtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='TAG',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=50),
        ),
    ]
