# Generated by Django 4.0.3 on 2022-03-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0002_alter_book_author_alter_book_book_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AUTHOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='BOOK_INDEX',
            field=models.TextField(blank=True, verbose_name='목차'),
        ),
        migrations.AlterField(
            model_name='book',
            name='BOOK_INTRODUCTION',
            field=models.TextField(blank=True, null=True, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='PUBLISHER',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
