# Generated by Django 4.0.3 on 2022-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0003_alter_authenticationcodestorage_atcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginMethod',
            field=models.IntegerField(default=0),
        ),
    ]
