# Generated by Django 4.0.3 on 2022-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0003_alter_book_author_alter_book_book_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BOOK_INDEX',
            field=models.TextField(blank=True, null=True, verbose_name='목차'),
        ),
    ]
