# Generated by Django 4.0.3 on 2022-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0005_book_thumbnailimage_alter_user_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwToken',
            field=models.TextField(blank=True),
        ),
    ]
