# Generated by Django 4.0.3 on 2022-04-07 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0006_book_thumbnailimage_alter_user_pwtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='contents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=10000000),
        ),
    ]
