# Generated by Django 4.0.3 on 2022-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0007_book_thumbnailimage_tag_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='anycommunity',
            name='title',
            field=models.CharField(default='임시제목입니다.', max_length=255),
        ),
        migrations.AddField(
            model_name='marketcommunity',
            name='title',
            field=models.CharField(default='임시제목입니다.', max_length=255),
        ),
        migrations.AddField(
            model_name='qnacommunity',
            name='parentQPID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qnacommunity',
            name='title',
            field=models.CharField(default='임시제목입니다.', max_length=255),
        ),
    ]
