# Generated by Django 4.0.3 on 2022-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0009_book_thumbnailimage_alter_anycommunity_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycomment',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anycomment',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anycommunity',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anycommunity',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='createAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
    ]
