# Generated by Django 4.0.3 on 2022-04-17 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0011_book_thumbnailimage_alter_anycommunity_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
        migrations.AlterField(
            model_name='review',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=10000000),
        ),
    ]
