# Generated by Django 4.0.3 on 2022-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0016_book_thumbnailimage_alter_anycommunity_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=2.5),
        ),
    ]
