# Generated by Django 4.0.3 on 2022-04-30 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0017_book_thumbnailimage_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], null=True, size=10000000),
        ),
    ]
