# Generated by Django 4.0.3 on 2022-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0020_imagestorage_book_thumbnailimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='test'),
        ),
    ]
