# Generated by Django 4.0.3 on 2022-05-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0021_book_thumbnailimage_alter_imagestorage_imagefile'),
    ]

    operations = [

        migrations.AlterField(
            model_name='imagestorage',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=models.BigAutoField(primary_key=True, serialize=False)),
        ),
    ]
