# Generated by Django 4.0.3 on 2022-05-12 21:45

import bookky.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0023_book_thumbnailimage_alter_imagestorage_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=bookky.models.image_upload_path),
        ),
    ]
