# Generated by Django 4.0.3 on 2022-05-12 21:52

import bookky.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0024_book_thumbnailimage_alter_imagestorage_imagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageStorage',
        ),
        migrations.AddField(
            model_name='user',
            name='imageContent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=bookky.models.image_user_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='imageTitle',
            field=models.TextField(null=True),
        ),
    ]
