# Generated by Django 4.0.3 on 2022-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0025_delete_imagestorage_book_thumbnailimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageFile',
        ),

    ]
