# Generated by Django 4.0.3 on 2022-05-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0026_remove_user_imagefile_book_thumbnailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotcommunity',
            name='communityType',
            field=models.IntegerField(default=0),
        ),
    ]
