# Generated by Django 4.0.3 on 2022-05-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0027_book_thumbnailimage_hotcommunity_communitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnacommunity',
            name='parentQPID',
            field=models.IntegerField(),
        ),
    ]
