# Generated by Django 4.0.3 on 2022-05-13 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0028_book_thumbnailimage_alter_qnacommunity_parentqpid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotcommunity',
            name='createAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotcommunity',
            name='updateAt',
            field=models.DateField(auto_now=True),
        ),
    ]
