# Generated by Django 4.0.3 on 2022-05-24 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0030_tagmodel_book_thumbnailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBook',
            fields=[
                ('TBID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=255)),
                ('SUBTITLE', models.CharField(max_length=255, null=True)),
                ('AUTHOR', models.CharField(blank=True, max_length=100, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=30, null=True)),
                ('PUBLISHER', models.CharField(blank=True, max_length=255, null=True)),
                ('PRICE', models.CharField(max_length=30, null=True)),
                ('PAGE', models.CharField(max_length=20, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('BOOK_INDEX', models.TextField(blank=True, null=True, verbose_name='목차')),
                ('BOOK_INTRODUCTION', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('PUBLISH_DATE', models.CharField(max_length=30, null=True)),
                ('TAG', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=50)),
                ('RATING', models.FloatField(default=2.5)),
                ('Allah_BID', models.CharField(max_length=30, null=True)),
                ('thumbnailImage', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
