# Generated by Django 4.0.3 on 2022-05-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0032_book_thumbnailimage_tempbook_searchname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendbook',
            old_name='BID',
            new_name='TBID',
        ),
        migrations.RenameField(
            model_name='tagmodel',
            old_name='name',
            new_name='nameTag',
        ),
        migrations.RemoveField(
            model_name='anycommunity',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='marketcommunity',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='qnacommunity',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='recommendbook',
            name='TID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='BID',
        ),
        migrations.AddField(
            model_name='anycommunity',
            name='TBID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='TBID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AddField(
            model_name='marketcommunity',
            name='TBID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AddField(
            model_name='qnacommunity',
            name='TBID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AddField(
            model_name='recommendbook',
            name='TMID',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='bookky.tagmodel'),
        ),
        migrations.AddField(
            model_name='review',
            name='TBID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
