# Generated by Django 4.0.3 on 2022-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0033_rename_bid_recommendbook_tbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycomment',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anycomment',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anycommunity',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anycommunity',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authenticationcodestorage',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotcommunity',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotcommunity',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='refreshtokenstorage',
            name='createAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
