# Generated by Django 4.0.3 on 2022-06-01 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0034_alter_anycomment_createat_alter_anycomment_updateat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycommunity',
            name='postImage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=6),
        ),
    ]
