# Generated by Django 4.0.3 on 2022-06-01 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0035_alter_anycommunity_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycommunity',
            name='postImage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=[], null=True, size=6),
        ),
    ]
