# Generated by Django 4.0.3 on 2022-06-02 00:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0038_alter_anycomment_like_alter_marketcomment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], size=10000000),
        ),
        migrations.AlterField(
            model_name='marketcomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], size=10000000),
        ),
        migrations.AlterField(
            model_name='qnacomment',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], size=10000000),
        ),
        migrations.AlterField(
            model_name='review',
            name='like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[], size=10000000),
        ),
    ]
