# Generated by Django 4.0.3 on 2022-07-07 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0040_alter_tempbook_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycommunity',
            name='postImage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=[], null=True, size=6),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='postImage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=[], null=True, size=6),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='postImage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, default=[], null=True, size=6),
        ),
    ]
