# Generated by Django 4.0.3 on 2022-07-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0041_alter_anycommunity_postimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycommunity',
            name='TBID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AlterField(
            model_name='marketcommunity',
            name='TBID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
        migrations.AlterField(
            model_name='qnacommunity',
            name='TBID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.tempbook'),
        ),
    ]
