# Generated by Django 4.0.3 on 2022-08-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0042_alter_anycommunity_tbid_alter_marketcommunity_tbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('SUID', models.BigAutoField(primary_key=True, serialize=False)),
                ('authority', models.IntegerField(default=5)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookky.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingTable',
            fields=[
                ('ReportId', models.BigAutoField(primary_key=True, serialize=False)),
                ('TYPE', models.IntegerField()),
                ('reportType', models.IntegerField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('reportContent', models.TextField(blank=True, verbose_name='신고 내용')),
                ('ACID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.anycomment')),
                ('APID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.anycommunity')),
                ('MCID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.marketcomment')),
                ('MPID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.marketcommunity')),
                ('QCID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.qnacomment')),
                ('QPID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookky.qnacommunity')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookky.user')),
            ],
        ),
    ]
