# Generated by Django 4.0.3 on 2022-08-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookky', '0043_superuser_reportingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingtable',
            name='reportContent',
        ),
    ]
